baseURL: https://adie-hub.github.io
languageCode: en-us
defaultContentLanguage: en
title: Adie Hub
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Adie-organized resources for Ada students and alum.
  homeMetaContent: Adie-organized resources for Ada students and alum.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to Github Pages.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: true
  moveFooterToHeader: false
  navTitleText: Adie Hub
  # logoAlt: An alternative text description of the logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: All Pages
      url: /post/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: Ask an Adie
      url: /ask-an-adie/
      weight: 4
    - name: Tags
      url: /tags/
      weight: 5
    - name: Contributing
      url: /contributing/
      weight: 6


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
